from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('email',sa.String(180),nullable=False,unique=True),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.String(30),nullable=False),sa.Column('active',sa.Boolean,nullable=False,server_default='true'),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('suppliers',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name',sa.String(180),nullable=False),sa.Column('phone',sa.String(40)),sa.Column('email',sa.String(180)),sa.Column('address',sa.Text),sa.Column('active',sa.Boolean,nullable=False,server_default='true'))
 op.create_table('products',sa.Column('id',sa.Integer,primary_key=True),sa.Column('sku',sa.String(60),nullable=False,unique=True),sa.Column('name',sa.String(180),nullable=False),sa.Column('category',sa.String(100),nullable=False),sa.Column('size',sa.String(30)),sa.Column('color',sa.String(50)),sa.Column('purchase_price',sa.Numeric(12,2),nullable=False),sa.Column('selling_price',sa.Numeric(12,2),nullable=False),sa.Column('stock',sa.Integer,nullable=False),sa.Column('reorder_level',sa.Integer,nullable=False),sa.Column('supplier_id',sa.Integer,sa.ForeignKey('suppliers.id',ondelete='SET NULL')),sa.Column('active',sa.Boolean,nullable=False,server_default='true'),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('purchases',sa.Column('id',sa.Integer,primary_key=True),sa.Column('supplier_id',sa.Integer,sa.ForeignKey('suppliers.id'),nullable=False),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('quantity',sa.Integer,nullable=False),sa.Column('unit_cost',sa.Numeric(12,2),nullable=False),sa.Column('total',sa.Numeric(12,2),nullable=False),sa.Column('purchased_at',sa.DateTime,nullable=False))
 op.create_table('invoices',sa.Column('id',sa.Integer,primary_key=True),sa.Column('invoice_no',sa.String(40),nullable=False,unique=True),sa.Column('staff_id',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('subtotal',sa.Numeric(12,2),nullable=False),sa.Column('discount',sa.Numeric(12,2),nullable=False),sa.Column('tax',sa.Numeric(12,2),nullable=False),sa.Column('total',sa.Numeric(12,2),nullable=False),sa.Column('payment_method',sa.String(30),nullable=False),sa.Column('paid_amount',sa.Numeric(12,2),nullable=False),sa.Column('change_amount',sa.Numeric(12,2),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('invoice_items',sa.Column('id',sa.Integer,primary_key=True),sa.Column('invoice_id',sa.Integer,sa.ForeignKey('invoices.id',ondelete='CASCADE'),nullable=False),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('product_name',sa.String(180),nullable=False),sa.Column('quantity',sa.Integer,nullable=False),sa.Column('unit_price',sa.Numeric(12,2),nullable=False),sa.Column('line_total',sa.Numeric(12,2),nullable=False))
 op.create_table('returns',sa.Column('id',sa.Integer,primary_key=True),sa.Column('invoice_id',sa.Integer,sa.ForeignKey('invoices.id'),nullable=False),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('quantity',sa.Integer,nullable=False),sa.Column('refund_amount',sa.Numeric(12,2),nullable=False),sa.Column('reason',sa.String(255),nullable=False),sa.Column('processed_by',sa.Integer,sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False))
 op.create_table('ledger_entries',sa.Column('id',sa.Integer,primary_key=True),sa.Column('entry_type',sa.String(30),nullable=False),sa.Column('reference',sa.String(80),nullable=False),sa.Column('description',sa.String(255),nullable=False),sa.Column('amount',sa.Numeric(12,2),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False))
def downgrade():
 for t in ['ledger_entries','returns','invoice_items','invoices','purchases','products','suppliers','users']: op.drop_table(t)
