import{useEffect,useState}from'react';import{Link,Route,Routes}from'react-router-dom';import{api,money}from'../lib/api';import Layout from'../components/Layout';import{Card,Empty,Page}from'../components/Ui';
function locationBase(){return window.location.pathname.startsWith("/admin/mobile")?"/admin/mobile":"/admin"}
function Dashboard(){const[d,setD]=useState<any>();const[bills,setBills]=useState<any[]>([]);const isMobile=locationBase()==='/admin/mobile';useEffect(()=>{api.get('/reports/dashboard').then(r=>setD(r.data));if(isMobile)api.get('/billing/invoices').then(r=>setBills(r.data.slice(0,4)))},[isMobile]);if(isMobile)return <Page title="Dashboard"><div className="mobile-dashboard-stats"><Card><small>Gross sales</small><strong>{money(Number(d?.gross_sales??0))}</strong></Card><Card><small>Today sales</small><strong>{money(Number(d?.today_sales??0))}</strong></Card><Card><small>Orders today</small><strong>{d?.today_bills??0}</strong></Card><Card><small>Low stock</small><strong className={Number(d?.low_stock??0)>0?'mobile-low-count':''}>{d?.low_stock??0}</strong><span className="mobile-stat-hint">Items below 10 units</span></Card></div><Card><div className="mobile-section-head"><h3>Recent Counter Bills</h3><Link to="/admin/mobile/transactions">View All</Link></div>{bills.length?bills.map(x=><div className="mobile-bill-row" key={x.id}><div><b>{x.invoice_no}</b><small>{x.customer_name||'Walk-in customer'} · {x.payment_method}</small></div><strong>{money(x.total)}</strong></div>):<Empty text="No recent bills"/>}</Card></Page>;return <Page title="Dashboard"><div className="stats">{[['Today sales',d?.today_sales??0],['Bills today',d?.today_bills??0],['Returns',d?.today_returns??0],['Low stock',d?.low_stock??0]].map(([a,b])=><Card key={String(a)}><small>{a}</small><strong>{a==='Today sales'||a==='Returns'?money(Number(b)):b}</strong></Card>)}</div><Card><h3>Quick actions</h3><div className="quick"><Link to={locationBase()+"/products"}>Manage products</Link><Link to={locationBase()+"/suppliers"}>Record purchase</Link><Link to={locationBase()+"/returns"}>Process return</Link><Link to={locationBase()+"/transactions"}>View transactions</Link></div></Card></Page>}
function Products(){const[rows,setRows]=useState<any[]>([]);const[q,setQ]=useState('');const[editing,setEditing]=useState<number|null|undefined>(undefined);const[form,setForm]=useState<any>({sku:'',name:'',category:'',size:'',color:'',purchase_price:0,selling_price:0,stock:0,reorder_level:5});const emptyForm=()=>({sku:'',name:'',category:'',size:'',color:'',purchase_price:0,selling_price:0,stock:0,reorder_level:5});const load=()=>api.get('/products',{params:{q}}).then(r=>setRows(r.data));useEffect(()=>{load()},[q]);function start(p?:any){setEditing(p ? p.id : null);setForm(p?{...p}:emptyForm())}function close(){setEditing(undefined);setForm(emptyForm())}async function save(e:any){e.preventDefault();try{if(editing!==undefined && editing!==null)await api.put('/products/'+editing,form);else await api.post('/products',form);close();load()}catch(e:any){alert(e.response?.data?.detail||'Save failed')}}return <Page title="Products" action={<button className="primary" onClick={()=>start()}>+ Product</button>}><Card><input className="search" placeholder="Search name, SKU or category…" value={q} onChange={e=>setQ(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th/></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.sku}</td><td><b>{p.name}</b><small>{p.size||'—'} · {p.color||'—'}</small></td><td>{p.category}</td><td>{money(p.selling_price)}</td><td><span className={p.stock<10?'pill warn':'pill'}>{p.stock}</span></td><td><button className="linkbtn" onClick={()=>start(p)}>Edit</button></td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></Card>{editing!==undefined&&<div className="modal"><form className="modal-card" onSubmit={save}><h2>{editing===null?'New product':'Edit product'}</h2>{['sku','name','category','size','color'].map(k=><label key={k}>{k.replace('_',' ')}<input value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})} required={['sku','name','category'].includes(k)}/></label>)}<div className="grid2">{['purchase_price','selling_price','stock','reorder_level'].map(k=><label key={k}>{k.replace('_',' ')}<input type="number" min="0" step="0.01" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}</div><div className="actions modal-actions"><button type="button" className="danger-button" onClick={close}>Cancel</button><button type="submit" className="primary modal-action-button">Save</button></div></form></div>}</Page>}
function Staff(){
 const [rows,setRows]=useState<any[]>([]);
 const [form,setForm]=useState<any>({name:'',email:'',password:'',role:'billing_staff',active:true});
 const [editing,setEditing]=useState<number|null>(null);
 const load=()=>api.get('/staff').then(r=>setRows(r.data));
 useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();try{if(editing!==null && editing>0){await api.put('/staff/'+editing,form)}else{await api.post('/staff',form)}setEditing(null);setForm({name:'',email:'',password:'',role:'billing_staff',active:true});load()}catch(e:any){alert(e.response?.data?.detail||'Save failed')}}
 return <Page title="Staff" action={<button className="primary" onClick={()=>setEditing(0)}>+ Staff</button>}>
  <Card><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.email}</td><td>{x.role}</td><td><span className="pill">{x.active?'Active':'Inactive'}</span></td><td><button className="linkbtn" onClick={()=>{setEditing(x.id);setForm({...x,password:''})}}>Edit</button></td></tr>)}</tbody></table></div></Card>
  {editing!==null ? <div className="modal"><form className="modal-card" onSubmit={save}><h2>{editing>0?'Edit staff':'New staff'}</h2><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required={editing===0}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="billing_staff">Billing Staff</option><option value="admin">Admin</option></select></label><label>Active<select value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Inactive</option></select></label><div className="actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary">Save</button></div></form></div> : null}
 </Page>
}
function Suppliers(){
 const[rows,setRows]=useState<any[]>([]);const[products,setProducts]=useState<any[]>([]);const[form,setForm]=useState<any>({name:'',phone:'',email:'',address:'',active:true});const[editing,setEditing]=useState<number|null>(null);const[purchase,setPurchase]=useState<any>({supplier_id:'',product_id:'',quantity:1,unit_cost:0});
 const load=()=>api.get('/suppliers').then(r=>setRows(r.data));
 useEffect(()=>{load();api.get('/products').then(r=>setProducts(r.data))},[]);
 async function save(e:any){e.preventDefault();try{editing?await api.put('/suppliers/'+editing,form):await api.post('/suppliers',form);setEditing(null);setForm({name:'',phone:'',email:'',address:'',active:true});load()}catch(e:any){alert(e.response?.data?.detail||'Save failed')}}
 async function buy(e:any){e.preventDefault();try{await api.post('/suppliers/purchases',{...purchase,supplier_id:Number(purchase.supplier_id),product_id:Number(purchase.product_id),quantity:Number(purchase.quantity),unit_cost:Number(purchase.unit_cost)});alert('Purchase recorded and stock updated');setPurchase({...purchase,quantity:1,unit_cost:0})}catch(e:any){alert(e.response?.data?.detail||'Purchase failed')}}
 return <Page title="Suppliers" action={<button className="primary" onClick={()=>setEditing(0)}>+ Supplier</button>}><div className="split"><div><Card><h3>{editing!==null?'Supplier details':'Add supplier'}</h3><form onSubmit={save}>{['name','phone','email','address'].map(k=><label key={k}>{k}<input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==='name'}/></label>)}{editing!==null&&editing>0&&<label>Active<select value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Inactive</option></select></label>}<div className="actions">{editing!==null&&<button type="button" onClick={()=>setEditing(null)}>Cancel</button>}<button className="primary">Save supplier</button></div></form></Card><Card><h3>Record purchase</h3><form onSubmit={buy}><label>Supplier<select value={purchase.supplier_id} onChange={e=>setPurchase({...purchase,supplier_id:e.target.value})} required><option value="">Select supplier</option>{rows.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Product<select value={purchase.product_id} onChange={e=>{const p=products.find(x=>x.id===Number(e.target.value));setPurchase({...purchase,product_id:e.target.value,unit_cost:p?.purchase_price||0})}} required><option value="">Select product</option>{products.map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select></label><div className="grid2"><label>Quantity<input type="number" min="1" value={purchase.quantity} onChange={e=>setPurchase({...purchase,quantity:Number(e.target.value)})}/></label><label>Unit cost<input type="number" min="0" step="0.01" value={purchase.unit_cost} onChange={e=>setPurchase({...purchase,unit_cost:Number(e.target.value)})}/></label></div><button className="primary full">Record purchase</button></form></Card></div><Card><h3>Suppliers</h3>{rows.map(x=><div className="listrow" key={x.id}><div><b>{x.name}</b><small>{x.phone||'No phone'} · {x.email||'No email'} · {x.active?'Active':'Inactive'}</small></div><button className="linkbtn" onClick={()=>{setEditing(x.id);setForm(x)}}>Edit</button></div>)}</Card></div></Page>
}
function Returns(){
 const[rows,setRows]=useState<any[]>([]);const[invoices,setInvoices]=useState<any[]>([]);const[form,setForm]=useState({invoice_id:'',product_id:'',quantity:1,reason:'Customer return'});const[busy,setBusy]=useState(false);
 const load=async()=>{try{const[r,i]=await Promise.all([api.get('/returns'),api.get('/billing/invoices')]);setRows(r.data);setInvoices(i.data)}catch(e:any){alert(e.response?.data?.detail||'Could not load return data')}};
 useEffect(()=>{load()},[]);
 const selectedInvoice=invoices.find(x=>x.id===Number(form.invoice_id));
 const selectedProduct=selectedInvoice?.items?.find((x:any)=>x.product_id===Number(form.product_id));
 const returnedQty=rows.filter(r=>r.invoice_id===Number(form.invoice_id)&&r.product_id===Number(form.product_id)).reduce((sum:number,r:any)=>sum+Number(r.quantity),0);
 const remaining=Math.max(0,Number(selectedProduct?.quantity||0)-returnedQty);
 function selectInvoice(value:string){setForm({...form,invoice_id:value,product_id:'',quantity:1})}
 async function submit(e:any){e.preventDefault();if(!form.invoice_id||!form.product_id||remaining<1)return;setBusy(true);try{await api.post('/returns',{invoice_id:Number(form.invoice_id),product_id:Number(form.product_id),quantity:Number(form.quantity),reason:form.reason.trim()||'Customer return'});setForm({invoice_id:'',product_id:'',quantity:1,reason:'Customer return'});await load();alert('Return processed successfully')}catch(e:any){const detail=e.response?.data?.detail;if(Array.isArray(detail))alert(detail.map((x:any)=>`${x.loc?.join('.')||'field'}: ${x.msg}`).join('\n'));else alert(detail||'Return failed')}finally{setBusy(false)}}
 return <Page title="Product Returns"><div className="split"><Card><h3>Process return</h3><form onSubmit={submit}>
  <label>Invoice<select value={form.invoice_id} onChange={e=>selectInvoice(e.target.value)} required><option value="">Select invoice</option>{invoices.map((x:any)=><option key={x.id} value={x.id}>{x.invoice_no} · {money(x.total)} · {new Date(x.created_at).toLocaleDateString()}</option>)}</select></label>
  <label>Product<select value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value,quantity:1})} disabled={!selectedInvoice} required><option value="">Select product</option>{selectedInvoice?.items?.map((x:any)=><option key={x.product_id} value={x.product_id}>{x.product_name} · Qty sold {x.quantity}{rows.some(r=>r.invoice_id===selectedInvoice.id&&r.product_id===x.product_id)?` · Remaining ${Math.max(0,x.quantity-rows.filter(r=>r.invoice_id===selectedInvoice.id&&r.product_id===x.product_id).reduce((s:number,r:any)=>s+r.quantity,0))}`:''}</option>)}</select></label>
  {selectedProduct&&<div className="return-info"><span>Sold: <b>{selectedProduct.quantity}</b></span><span>Already returned: <b>{returnedQty}</b></span><span>Returnable: <b>{remaining}</b></span></div>}
  <label>Quantity<input type="number" min="1" max={remaining||1} value={form.quantity} disabled={!selectedProduct||remaining<1} onChange={e=>setForm({...form,quantity:Math.min(remaining||1,Math.max(1,Number(e.target.value)||1))})}/></label>
  <label>Reason<input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} required/></label>
  <button className="primary full" disabled={busy||!selectedProduct||remaining<1}>{busy?'Processing…':'Process return'}</button>
 </form></Card><Card><h3>Recent returns</h3>{rows.length?rows.map(r=><div className="listrow" key={r.id}><div><b>Invoice #{r.invoice_id}</b><small>Product {r.product_id} · Qty {r.quantity} · {r.reason}</small></div><strong>{money(r.refund_amount)}</strong></div>):<Empty text="No returns yet"/>}</Card></div></Page>}
function Transactions(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api.get('/billing/invoices').then(r=>setRows(r.data))},[]);return <Page title="Billing & Transactions"><Card><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Date</th><th>Items</th><th>Payment</th><th>Total</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.invoice_no}</b></td><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.items.length}</td><td>{x.payment_method}</td><td>{money(x.total)}</td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div></Card></Page>}
function Reports(){const[d,setD]=useState<any>();const[l,setL]=useState<any[]>([]);useEffect(()=>{Promise.all([api.get('/reports/dashboard'),api.get('/reports/ledger')]).then(([a,b])=>{setD(a.data);setL(b.data)})},[]);return <Page title="Ledger & Reports"><div className="stats">{[['Sales today',money(d?.today_sales||0)],['Bills',d?.today_bills||0],['Returns',money(d?.today_returns||0)],['Low stock',d?.low_stock||0]].map(([a,b])=><Card key={String(a)}><small>{a}</small><strong>{b}</strong></Card>)}</div><Card><h3>Ledger</h3>{l.map(x=><div className="listrow" key={x.id}><div><b>{x.description}</b><small>{x.entry_type} · {new Date(x.created_at).toLocaleString()}</small></div><strong className={x.amount<0?'negative':''}>{money(x.amount)}</strong></div>)}</Card></Page>}
function AdminRoutes(){return <Routes><Route index element={<Dashboard/>}/><Route path="products" element={<Products/>}/><Route path="staff" element={<Staff/>}/><Route path="suppliers" element={<Suppliers/>}/><Route path="returns" element={<Returns/>}/><Route path="transactions" element={<Transactions/>}/><Route path="reports" element={<Reports/>}/></Routes>}
function MobileAdmin(){return <Layout mobile><Routes><Route index element={<Dashboard/>}/><Route path="products" element={<Products/>}/><Route path="staff" element={<Staff/>}/><Route path="suppliers" element={<Suppliers/>}/><Route path="returns" element={<Returns/>}/><Route path="transactions" element={<Transactions/>}/><Route path="reports" element={<Reports/>}/></Routes></Layout>}
export default function Admin(){return <><Routes><Route path="mobile/*" element={<MobileAdmin/>}/><Route path="*" element={<Layout><AdminRoutes/></Layout>}/></Routes></>}
